# Generated by Django 4.2.3 on 2023-08-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_project_options_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pourcentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
