# Generated by Django 4.2.3 on 2023-08-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_pourcentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='attachement',
            new_name='attachment',
        ),
    ]
