# Generated by Django 4.2.3 on 2023-08-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_notification_readers_alter_notification_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='body',
        ),
    ]
