# Generated by Django 4.2.3 on 2023-08-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_notification_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
    ]
